parameters:
#    kfc_test.example.class: Kfc\TestBundle\Example

services:
#    kfc_test.example:
#        class: %kfc_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
